last minute changes are never good
ok, so this will get delayed. but it needs to happen. trying to simplify
the fsplit func and get cksumit to work nicely with Makefile. almost
there.

diff --git a/main/extra_functions b/main/extra_functions
--- a/main/extra_functions
+++ b/main/extra_functions
@@ -2,12 +2,11 @@
 #help: usage : cksumit file [file ...]
 function cksumit () {
     for x in $@; do
-        while read; do
+        while read -r; do
             ck=$(echo $REPLY | tr -d '[[:space:]]' | sum)
             echo ${ck%% *} "$REPLY"
         done < $x
         echo ''
-        md5sum $x
     done
 }
 
@@ -29,24 +28,20 @@ function ffix ()
 }
 
 #help: fsplit : splits a file of functions into a dir of separate functions
-#help: usage : fsplit path dest
-#help: : fsplit path (n.b. dest derived from path)
-#help: : fsplit (n.b. uses $MAINDIR/prime_functions by default)
+#help: usage : fsplit file [dir]
 function fsplit () {
-    [[ $# -gt 0 ]] || set - $MAINDIR/prime_functions
     [[ ${1##*_} = functions ]] || { echo input file not a functions file; return 1; }
-    declare inputFile=${1##*/}
-    declare -x outputDir=${2:-${inputFile%_*}}
+    [[ -s $1 ]] || { echo "can not find <$1>"; return 1; }
+    declare -x outputDir=${2:-${1%_*}}
     [[ -d $outputDir ]] && { echo dir for $outputDir already exists; return 1; }
     mkdir $outputDir &>/dev/null || { echo "can't make dir $outputDir"; return 1; }
-    (
-	cd $outputDir &>/dev/null || { echo "can't cd into dir $outputDir"; return 1; }
-	csplit -s -z $1 /^$/ {*}
-	for x in *; do
-	    new=$(awk '/^function / {print $2;exit}' $x)
-	    mv $x $new
-	done
-    )
+    csplit -s -z --prefix=$outputDir/xx $1 /^$/ {*}
+    pushd $outputDir &>/dev/null || { echo "can't cd into dir $outputDir"; return 1; }
+    for x in *; do
+        new=$(awk '/^function / {print $2;exit}' $x)
+        mv $x $new
+    done
+    popd &>/dev/null
 }
 
 #help: gigify : converts numbers to a different unit
