commiting some changes so we can start testing
i need to commit this so i can pull SetPrompt from the master branch

diff --git a/main/functions b/main/functions
--- a/main/functions
+++ b/main/functions
@@ -65,43 +65,60 @@ function _FixList ()
     printf '%s\n' "${list[@]}"
 }
 
-#help: envpurge : reset the environment
-function envpurge ()
-{
-    complete -r
-    unalias -a
-    unset -f $(compgen -A function) &>/dev/null
-}
+##help: envpurge : reset the environment
+#function envpurge ()
+#{
+#    complete -r
+#    unalias -a
+#    unset -f $(compgen -A function) &>/dev/null
+#}
+#
+##help: _flistXpnd : expands the contents of FLIST by prepending the path to
+##help: : the name
+#function _flistXpnd ()
+#{
+#    grep -o -P '^\w+' $FLISTDIR/FLIST | sed "s|^|$FLISTDIR/|"
+#}
+#
+##help: _flistFind : finds the file that contains the function
+#function _flistFind ()
+#{
+#    declare x dir
+#    for x in $@; do
+#	[[ -f $FLISTDIR/$x ]] && echo $FLISTDIR/$x || continue
+#    done
+#}
+#
+##help: load : loads the given function names found in FLISTDIR or
+##help: : the given full path
+#function load () {
+#    declare x y
+#    [[ $# -gt 0 ]] || envpurge
+#    for x in ${@:-$(_flistXpnd)}; do
+#	[[ -f ${y:=$x} ]] || y=$(_flistFind $x)
+#	[[ -n $y ]] && . $y || { echo "can't find $x"; continue; }
+#	[[ -f ~/.quiet ]] && echo -n . || echo $y
+#    done
+#    echo ' done'
+#}
 
-#help: _flistXpnd : expands the contents of FLIST by prepending the path to
-#help: : the name
-function _flistXpnd ()
-{
-    grep -o -P '^\w+' $FLISTDIR/FLIST | sed "s|^|$FLISTDIR/|"
-}
-
-#help: _flistFind : finds the file that contains the function
-function _flistFind ()
-{
-    declare x dir
-    for x in $@; do
-	[[ -f $FLISTDIR/$x ]] && echo $FLISTDIR/$x || continue
-    done
-}
-
-#help: load : loads the given function names found in FLISTDIR or
+#help: load : loads the given functions
 #help: : the given full path
-function load () {
-    declare x y
-    [[ $# -gt 0 ]] || envpurge
-    for x in ${@:-$(_flistXpnd)}; do
-	[[ -f ${y:=$x} ]] || y=$(_flistFind $x)
-	[[ -n $y ]] && . $y || { echo "can't find $x"; continue; }
-	[[ -f ~/.quiet ]] && echo -n . || echo $y
+function load () { 
+    declare flist=$(echo ~/Git/Env/main/functions ~/Git/Env/main/extra_functions)
+    for x in $@; do
+	sed -nr "/^function $x /{:1;p;n;/^}/!b1;p;q}" $flist > /tmp/$x
+	. /tmp/$x
+	rm /tmp/$x
     done
-    echo ' done'
 }
 
+#help: hlistf : lists available functions
+#help: usage : hlistf
+function listf () {
+    declare flist=$(echo ~/Git/Env/main/functions ~/Git/Env/main/extra_functions)
+    awk '/^#help : [[:alpha:]]+ / {print $2}' $flist | cut -c8- | column -s: -t
+}
 
 #help: _ArgParser : argument completion function
 function _ArgParser () {
@@ -140,7 +157,6 @@ function L ()
         ls -$opts "$x"/.??* 2> /dev/null
     done
 }
-
 
 #help: setPrompt : : utility to set prompt line characteristics (alias as stp)
 #help: usage : setPrompt [args...]
@@ -227,7 +243,6 @@ function show ()
     fi
 }
 
-
 #help: commas : commafy numeric fields in input stream
 #help: usage : ... | commas
 function commas ()
@@ -255,7 +270,6 @@ function configEd () {
     esac
 }
 
-
 #help: ffix : useful to grab a function and edit it for testing
 #help: usage : ffix function (the edited file will be in /tmp)
 function ffix ()
@@ -266,7 +280,6 @@ function ffix ()
     . $x
 }
 
-
 #help: ffunc : presents defined functions and file they are from
 #help: usage : ffunc function
 function ffunc ()
@@ -276,14 +289,11 @@ function ffunc ()
     shopt -u extdebug
 }
 
-
 #help: hlp : help for loading functions
 #help: usage : hlp function
 function hlp () {
     sed -nr "/: $1 :/{:1;p;n;/^function/!b1}" $2 | cut -f2- -d: | column -n -s: -t
-    
 }
-
 
 #help: julian : presents dates in julian format and converts back
 #help: usage : julian [date]
@@ -309,7 +319,6 @@ function julian ()
     esac
 }
 
-
 #help: killdir : moves you to the parent and removes the dir you were in
 #help: usage : killdir
 function killdir ()
@@ -324,7 +333,6 @@ function killdir ()
     dirs -v
 }
 
-
 #help: lsu : a long listing of dirs moving up the dir path
 #help: usage : lsu
 function lsu ()
@@ -335,7 +343,6 @@ function lsu ()
     done
     ls -ld "${np[@]}"
 }
-
 
 #help: mkwdir : creates a new arg.nn dir based on arg
 #help: usage : mkwdir (base)
@@ -348,8 +355,6 @@ function mkwdir ()
     printf -v dir "%s.%02d" $pat $((1+count))
     mkdir -v $dir
 }
-
-
 
 #help: mydd : convenience wrapper for dd/dcfldd
 #help: usage : mydd object <tab> [option ...]
@@ -367,7 +372,6 @@ function mydd ()
 	    ;;
     esac
 }
-
 
 #help: prep : used to give a boilerplate file for editing
 #help: usage : prep file.(sh|pl|py|fn|fnc)
@@ -392,14 +396,12 @@ function prep ()
     done
 }
 
-
 #help: spx : simple function to do aspell
 #help: usage : spx word [word ...]
 function spx ()
 {
     echo $@ | aspell -a
 }
-
 
 #help: stk : dir stack operations to save, load and clear the dirstack
 #help: usage : stk [save|load] filename
